= Big headline of task
Author Name <author_name>; Author Email <email>; date <date>

== Description
*Context*: Context for problem/task

*Problem/Task*: Problem/task being tackled

*Solution/Result*: Solution/Result completed

*Implication*: Implication now that this solution/result exists

== Engineer Concerns:
*Prior relevant experience*:

*Doing for first time*:

*Engineering constraints*:

*Complexity factors*:
- Domain Changes?: Do you have to change the assumptions the codebase's domain has? What are they if you do?
- Event Changes?: Do you have to change the events that happen in the overall ecosystem? What are they if you do?
- System Changes?: Do you have to change the actual system that exist in the ecosystem? What changes if you do?
- How to prove work is done?: How can you demonstrate work was done in a clear black and white manner?

== Resources:
* |tutorial|: ...
* |how-to|: ...
* |explanation|: ...
* |reference|: ...

`vim type "!!date<CR>" for timestamp`

== Thought Process:

'''

*Lead*:

*Action*:

'''

*Current understanding*:

'''

*Update*:

'''

*Discovery*:

*Implication*:

'''

*Accomplished*: 

*What's next*: 

'''

*Drawn System reference diagram based on my understanding*

'''

*Event model for before work*: 

*How to show problem of not having work done*:

'''

*Event model for after work*:

*How to test to prove work was a success*:

*How to test to prove existing functionality isn't broken?*

'''

*Question*: 

- Idea: Based on (info), it's possible (that XYZ assertion is correct), (optional explanation)

  Outcome: When (ABC action was performed), (certain result happened), (optional analysis)

*Answer*: 

'''
