= Big headline of task
Author Name <author_name>; Author Email <email>; date <date>

== Description
*Context*: Context for problem/task

*Problem/Task*: Problem/task being tackled

*Solution/Result*: Solution/Result completed

*Implication*: Implication now that this solution/result exists

== Engineer Concerns:
*Prior relevant experience*:

*Doing for first time*:

*Lessons Learned*:

*Engineering constraints*:

*Complexity factors*:
- How to prove work is done?: How can you demonstrate work was done in a clear black and white manner? If this is complex chances are your work is going to be complex because of this bottleneck
- Domain Changes?: Do you have to change the assumptions the codebase's domain has? What are they if you do?
- Event Changes?: Do you have to change the events that happen in the overall ecosystem? What are they if you do?
- System Changes?: Do you have to change the actual system that exist in the ecosystem? What changes if you do?

== Resources:
* |tutorial|: ...
* |how-to|: ...
* |explanation|: ...
* |reference|: ...

`vim type "!!date<CR>" for timestamp`

== Engineering Phases:
* *Discovery*: Exploring the problem, researching relevant domain/subject matter space, understanding alternatives, ideal target audience if any, definition of quality
* *Shaping*: Working with relevant parties to write out use cases, define ideal experience and acceptable pragmatic to implement experience. What is definition of done.
* *Design*: Define clear product requirements including technical domain detail, craft final designs, create work plan, estimate timeline, define learning/test plan
* *Build*: Execute, test
* *Launch*: Monitor, follow up research

== Detailed Applied Engineering Phases:
* 

== Thought Process:

'''

*Lead*:

*Action*:

'''

*Current understanding*:

'''

*Update*:

'''

*Discovery*:

*Implication*:

'''

*Accomplished*: 

*What's next*: 

'''

*Drawn System reference diagram based on my understanding*

'''

*Event model for before work*: 

*How to show problem of not having work done*:

'''

*Event model for after work*:

*How to test to prove work was a success*:

*How to test to prove existing functionality isn't broken?*

'''

*Question*: 

- Idea: Based on (info), it's possible (that XYZ assertion is correct), (optional explanation)

  Outcome: When (ABC action was performed), (certain result happened), (optional analysis)

*Answer*: 

'''
